name: Build iOS IPA

on: 
  workflow_dispatch: 

jobs: 
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Generate Kotlin framework
      run: ./gradlew :shared:generateDummyFramework

    - name: Install CocoaPods
      run: |
        cd iosApp
        pod install

    - name: Build IPA (code signing disabled)
      run: |
        xcodebuild -workspace iosApp/iosApp.xcworkspace \
                   -scheme iosApp \
                   -sdk iphoneos \
                   -configuration Release \
                   -archivePath $PWD/build/iosApp.xcarchive \
                   archive \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGN_IDENTITY=""

        xcodebuild -exportArchive \
                   -archivePath $PWD/build/iosApp.xcarchive \
                   -exportPath $PWD/build/ipa \
                   -exportOptionsPlist iosApp/ExportOptions.plist \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGN_IDENTITY=""

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: iosApp.ipa
        path: build/ipa
